//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BashGah
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_GymEntities : DbContext
    {
        public DB_GymEntities()
            : base("name=DB_GymEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tbl_Athletes> Tbl_Athletes { get; set; }
        public virtual DbSet<Tbl_Factor> Tbl_Factor { get; set; }
        public virtual DbSet<Tbl_Store> Tbl_Store { get; set; }
        public virtual DbSet<Tbl_Wardrops> Tbl_Wardrops { get; set; }
    }
}
