//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BashGah
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_AdminAccess
    {
        public int AdminAccess_ID { get; set; }
        public string AdminAccess_UserName { get; set; }
        public string AdminAccess_PassWord { get; set; }
        public bool AdminAccess_AddMember { get; set; }
        public bool AdminAccess_ManageMember { get; set; }
        public bool AdminAccess_CaseHistory { get; set; }
        public bool AdminAccess_AddGoods { get; set; }
        public bool AdminAccess_ManageGoods { get; set; }
        public bool AdminAccess_SaleGoods { get; set; }
        public bool AdminAccess_ManageWardRobe { get; set; }
        public bool AdminAccess_ManageAdmin { get; set; }
        public bool AdminAccess_BackUp { get; set; }
        public bool AdminAccess_Restore { get; set; }
    }
}
