//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BashGah
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Wardrops
    {
        public int Wardrop_ID { get; set; }
        public string Wardrop_Number { get; set; }
        public string Wardrop_State { get; set; }
        public string Wardrop_AthleteName { get; set; }
    }
}
