//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BashGah
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Store
    {
        public int Store_FoodID { get; set; }
        public string Store_FoodName { get; set; }
        public string Store_FoodPrice { get; set; }
        public string Store_FoodInventory { get; set; }
    }
}
