//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BashGah
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Athlete
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Athlete()
        {
            this.Tbl_Factor = new HashSet<Tbl_Factor>();
        }
    
        public int Athlete_ID { get; set; }
        public string Athlete_FullName { get; set; }
        public string Athlete_BirthDay { get; set; }
        public string Athlete_JoinDate { get; set; }
        public string Athlete_ValidityDate { get; set; }
        public string Athlete_WardropNum { get; set; }
        public string Athlete_Address { get; set; }
        public string Athlete_PhoneNumber { get; set; }
        public string Athlete_Image { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Factor> Tbl_Factor { get; set; }
    }
}
