//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BashGah
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_Factor
    {
        public int Factor_ID { get; set; }
        public string Factor_Date { get; set; }
        public int Facotr_Price { get; set; }
        public int Athlete_ID { get; set; }
        public string Factor_Type { get; set; }
        public string Athlete_FullName { get; set; }
        public string AthleteName { get; set; }
    }
}
